/*
  Simple Identity changer, Level 9.
  Easy to use and should work.
  Lua U may have effected this, not been tested after Lua U.
  But before Lua U this used to make your Exploit's hook x4 times faster and the execution too as it has a whole new env to run on.
  
  Credits:
      Jaden Wester (Rewriting some bugs)
      Josh Svensson (Creator)
*/
bool sub_82E080(uintptr_t a1) {
    // Yes these are from Roblox's source code, do not touch Skiddo!
    // Just some simple ass math. Generated by IDA.
    int a2;
    int a3;
    int a4;
    int a6;
    a3 = 5 * 4;
    a4 = 13 * 2;
    DWORD* a5;
    a2 = a3 - 2 * 3;
    a6 = a2 - 5;
    try {
        a5 = (DWORD*)(a1 - a2); *a5 ^= (a6 ^ (unsigned __int8)* a5) & 0x1F; // Set's the Identity to 9 by solving the maths.
    }
    catch (std::exception e) {
        std::cout << "Identity error" << std::endl; // Error setting the Identity.
    }
    return true;
}
